# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Github\PyQt5_Applications\Normal\1_Calculator\source\calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 569)
        MainWindow.setMaximumSize(QtCore.QSize(421, 569))
        MainWindow.setBaseSize(QtCore.QSize(414, 439))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 397, 528))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.expression_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.expression_label.setMaximumSize(QtCore.QSize(395, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expression_label.setFont(font)
        self.expression_label.setText("")
        self.expression_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.expression_label.setObjectName("expression_label")
        self.verticalLayout.addWidget(self.expression_label)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 100))
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setDigitCount(20)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.one = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.one.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 4, 0, 1, 1)
        self.nine = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nine.setMaximumSize(QtCore.QSize(97, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 2, 2, 1, 1)
        self.multiplication = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.multiplication.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.multiplication.setFont(font)
        self.multiplication.setObjectName("multiplication")
        self.gridLayout.addWidget(self.multiplication, 2, 3, 1, 1)
        self.six = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.six.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 3, 2, 1, 1)
        self.seven = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.seven.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 2, 0, 1, 1)
        self.percent = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.percent.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.percent.setFont(font)
        self.percent.setObjectName("percent")
        self.gridLayout.addWidget(self.percent, 0, 2, 1, 1)
        self.three = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.three.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 4, 2, 1, 1)
        self.five = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.five.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 3, 1, 1, 1)
        self.two = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.two.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 4, 1, 1, 1)
        self.subtract = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.subtract.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.subtract.setFont(font)
        self.subtract.setObjectName("subtract")
        self.gridLayout.addWidget(self.subtract, 3, 3, 1, 1)
        self.clear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clear.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 0, 0, 1, 1)
        self.four = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.four.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 3, 0, 1, 1)
        self.eight = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.eight.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 2, 1, 1, 1)
        self.add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 4, 3, 1, 1)
        self.division = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.division.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.division.setFont(font)
        self.division.setObjectName("division")
        self.gridLayout.addWidget(self.division, 0, 3, 1, 1)
        self.sign = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sign.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sign.setFont(font)
        self.sign.setObjectName("sign")
        self.gridLayout.addWidget(self.sign, 0, 1, 1, 1)
        self.point = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.point.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.point.setFont(font)
        self.point.setObjectName("point")
        self.gridLayout.addWidget(self.point, 6, 2, 1, 1)
        self.equal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.equal.setMaximumSize(QtCore.QSize(94, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.gridLayout.addWidget(self.equal, 6, 3, 1, 1)
        self.zero = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 6, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.one.setText(_translate("MainWindow", "1"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.multiplication.setText(_translate("MainWindow", "×"))
        self.six.setText(_translate("MainWindow", "6"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.three.setText(_translate("MainWindow", "3"))
        self.five.setText(_translate("MainWindow", "5"))
        self.two.setText(_translate("MainWindow", "2"))
        self.subtract.setText(_translate("MainWindow", "-"))
        self.clear.setText(_translate("MainWindow", "AC"))
        self.four.setText(_translate("MainWindow", "4"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.add.setText(_translate("MainWindow", "+"))
        self.division.setText(_translate("MainWindow", "÷"))
        self.sign.setText(_translate("MainWindow", "±"))
        self.point.setText(_translate("MainWindow", "."))
        self.equal.setText(_translate("MainWindow", "="))
        self.zero.setText(_translate("MainWindow", "0"))

